import json
import logging
from typing import Any

from openai import AsyncOpenAI

from app.core.config import settings
from app.schemas.studio import StudioCampaignPlan, StudioScenePlan
from app.services.openai_client import get_async_openai_client

logger = logging.getLogger(__name__)


class StudioService:
    """Generates short-form campaign plans and scene directions for video stitching."""

    def __init__(self, client: AsyncOpenAI | None = None) -> None:
        self.client = client or get_async_openai_client()
        self.planning_model = settings.openai_studio_planning_model
        self.image_model = settings.openai_studio_image_model

    async def create_campaign_assets(
        self,
        *,
        product_title: str,
        product_description: str,
        bullet_highlights: list[str],
        seo_tags: list[str],
        background_context: str,
        visual_summary: str,
        product_category: str,
        fabric: str,
        color: str,
        pattern: str,
        source_image_bytes: bytes | None = None,
        source_image_content_type: str | None = None,
    ) -> dict[str, Any]:
        logger.info(
            "Studio planning started for '%s' using model '%s'",
            product_title,
            self.planning_model,
        )
        plan = await self._create_campaign_plan(
            product_title=product_title,
            product_description=product_description,
            bullet_highlights=bullet_highlights,
            seo_tags=seo_tags,
            background_context=background_context,
            visual_summary=visual_summary,
            product_category=product_category,
            fabric=fabric,
            color=color,
            pattern=pattern,
        )
        logger.info(
            "Studio planning completed for '%s'; generating %s frame(s)",
            product_title,
            3,
        )
        scene_plans = self._build_fixed_scene_descriptions(
            product_title=product_title,
            product_category=product_category,
            product_description=product_description,
            fabric=fabric,
            color=color,
            pattern=pattern,
        )

        total_duration_seconds = sum(
            scene.duration_seconds for scene in scene_plans
        )

        return {
            "campaign_concept": plan.campaign_concept,
            "ad_script": plan.ad_script,
            "scene_descriptions": [scene.model_dump() for scene in scene_plans],
            "image_sequence": [],
            "stitching_plan": {
                "recommended_fps": 24,
                "recommended_total_duration_seconds": total_duration_seconds,
                "recommended_resolution": "1536x1024",
                "frame_order": [
                    {
                        "scene_number": scene.scene_number,
                        "duration_seconds": scene.duration_seconds,
                    }
                    for scene in scene_plans
                ],
                "note": (
                    "These scene directions are prepared for stitching into a short video. "
                    "Still frames are generated by the dedicated image agent. No direct video API was used."
                ),
            },
        }

    async def _create_campaign_plan(
        self,
        *,
        product_title: str,
        product_description: str,
        bullet_highlights: list[str],
        seo_tags: list[str],
        background_context: str,
        visual_summary: str,
        product_category: str,
        fabric: str,
        color: str,
        pattern: str,
    ) -> StudioCampaignPlan:
        response = await self.client.responses.create(
            model=self.planning_model,
            input=[
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "input_text",
                            "text": self._build_planning_prompt(
                                product_title=product_title,
                                product_description=product_description,
                                bullet_highlights=bullet_highlights,
                                seo_tags=seo_tags,
                                background_context=background_context,
                                visual_summary=visual_summary,
                                product_category=product_category,
                                fabric=fabric,
                                color=color,
                                pattern=pattern,
                            ),
                        }
                    ],
                }
            ],
            temperature=0.7,
            max_output_tokens=1200,
        )
        payload = self._parse_json_response(response.output_text)
        return StudioCampaignPlan.model_validate(payload)

    async def _generate_frame_image(
        self,
        *,
        prompt: str,
        scene_title: str,
        source_image_bytes: bytes | None,
        source_image_content_type: str | None,
    ) -> dict[str, Any]:
        strict_prompt = self._build_image_prompt(
            prompt=prompt,
            scene_title=scene_title,
        )
        candidate_models = self._candidate_image_models()
        image_response = None
        last_error: Exception | None = None
        generation_method: str | None = None
        generation_model: str | None = None

        for model_name in candidate_models:
            if source_image_bytes:
                try:
                    logger.info(
                        "Trying Studio image edit for scene '%s' with model '%s'",
                        scene_title,
                        model_name,
                    )
                    image_response = await self.client.images.edit(
                        model=model_name,
                        image=(
                            "source-image.png",
                            source_image_bytes,
                            source_image_content_type or "image/png",
                        ),
                        prompt=strict_prompt,
                        background="opaque",
                        input_fidelity="high",
                        size="auto",
                        quality="high",
                        output_format="png",
                        n=1,
                    )
                    generation_method = "edit"
                    generation_model = model_name
                    break
                except Exception as exc:
                    last_error = exc
                    image_response = None
                    logger.warning(
                        "Studio image edit failed for scene '%s' with model '%s': %s",
                        scene_title,
                        model_name,
                        exc,
                    )

            try:
                logger.info(
                    "Trying Studio image generation for scene '%s' with model '%s'",
                    scene_title,
                    model_name,
                )
                image_response = await self.client.images.generate(
                    model=model_name,
                    prompt=strict_prompt,
                    background="opaque",
                    size="1536x1024",
                    quality="high",
                    output_format="png",
                    n=1,
                )
                generation_method = "generate"
                generation_model = model_name
                break
            except Exception as exc:
                last_error = exc
                image_response = None
                logger.warning(
                    "Studio image generation failed for scene '%s' with model '%s': %s",
                    scene_title,
                    model_name,
                    exc,
                )

        if image_response is None:
            logger.error(
                "Studio image generation failed for scene '%s' after trying models %s",
                scene_title,
                candidate_models,
            )
            raise ValueError(
                f"Studio image generation failed for all candidate image models: {last_error}"
            )

        image_data = (image_response.data or [None])[0]
        if image_data is None or not image_data.b64_json:
            raise ValueError("Studio image generation did not return image data.")

        return {
            "frame_image_b64": image_data.b64_json,
            "revised_prompt": image_data.revised_prompt,
            "output_format": image_response.output_format or "png",
            "size": image_response.size or "1536x1024",
            "quality": image_response.quality or "high",
            "generation_model": generation_model or self.image_model,
            "generation_method": generation_method or "unknown",
            "source_image_used": bool(source_image_bytes and generation_method == "edit"),
        }

    def _candidate_image_models(self) -> list[str]:
        candidates = [
            self.image_model,
            "gpt-image-1.5",
            "gpt-image-1",
            "gpt-image-1-mini",
        ]
        deduped: list[str] = []
        for item in candidates:
            if item and item not in deduped:
                deduped.append(item)
        return deduped

    def _build_planning_prompt(
        self,
        *,
        product_title: str,
        product_description: str,
        bullet_highlights: list[str],
        seo_tags: list[str],
        background_context: str,
        visual_summary: str,
        product_category: str,
        fabric: str,
        color: str,
        pattern: str,
    ) -> str:
        return (
            "You are a premium brand creative director preparing a short product ad.\n"
            "Create a concise, luxurious campaign plan for a 10-15 second stitched video.\n"
            "Return JSON only with this exact schema:\n"
            "{\n"
            '  "campaign_concept": "string",\n'
            '  "ad_script": "string",\n'
            '  "scene_descriptions": [\n'
            "    {\n"
            '      "scene_number": 1,\n'
            '      "scene_title": "string",\n'
            '      "duration_seconds": 3,\n'
            '      "scene_description": "string",\n'
            '      "frame_prompt": "string",\n'
            '      "transition_note": "string"\n'
            "    }\n"
            "  ]\n"
            "}\n"
            "Rules:\n"
            "- Create exactly 3 scene descriptions.\n"
            "- Total duration should be between 10 and 15 seconds.\n"
            "- The ad script should feel cinematic, premium, and concise enough for a 10-15 second voiceover.\n"
            "- Each frame prompt must create a professional image to help sell the exact same product from the uploaded local camera image.\n"
            "- Preserve product continuity across all scenes.\n"
            "- Focus on product-first storytelling rather than generic lifestyle imagery.\n"
            "- Make the 3 scenes: 1) clean hero ecommerce shot, 2) premium detail close-up, 3) tasteful lifestyle/context shot.\n"
            f"Product title: {product_title}\n"
            f"Product category: {product_category}\n"
            f"Product description: {product_description}\n"
            f"Bullet highlights: {json.dumps(bullet_highlights)}\n"
            f"SEO tags: {json.dumps(seo_tags)}\n"
            f"Visual summary: {visual_summary}\n"
            f"Background context: {background_context}\n"
            f"Fabric: {fabric}\n"
            f"Color: {color}\n"
            f"Pattern: {pattern}\n"
        )

    def _build_image_prompt(self, *, prompt: str, scene_title: str) -> str:
        return (
            "Generate 1 professional ecommerce marketing image of the exact same product shown in the provided local camera image. "
            "Use the source image as the primary reference and preserve the same product identity, shape, fabric appearance, color accuracy, pattern, silhouette, scale, and design details. "
            "The result must look like a real catalog photo of the same item, not a new invention. "
            "Do not remove the product. Do not output an empty white frame. Do not output abstract gradients. Do not hallucinate extra objects that hide the item. "
            "Create a polished commercial product photograph with crisp focus, balanced lighting, natural shadows, premium styling, and a clean sales-oriented composition. "
            "The product must be centered or hero-framed and clearly visible.\n"
            f"Scene title: {scene_title}.\n"
            f"Scene direction: {prompt}"
        )

    def _build_fixed_scene_descriptions(
        self,
        *,
        product_title: str,
        product_category: str,
        product_description: str,
        fabric: str,
        color: str,
        pattern: str,
    ) -> list[StudioScenePlan]:
        descriptor = ", ".join(
            item for item in [color, fabric, pattern, product_category] if item
        ).strip(", ")
        subject_line = (
            f"{product_title}, a {descriptor}" if descriptor else product_title
        )

        return [
            StudioScenePlan(
                scene_number=1,
                scene_title="Hero Product Shot",
                duration_seconds=4,
                scene_description=(
                    f"A premium storefront hero image of {subject_line} with a clean, high-end ecommerce presentation."
                ),
                frame_prompt=(
                    f"Create a professional hero product shot of {subject_line}. "
                    "Use a clean studio background, balanced premium lighting, sharp focus, realistic texture, "
                    "and a luxury ecommerce catalog look. Show the full product clearly and prominently."
                ),
                transition_note="Open with the clearest full-product view.",
            ),
            StudioScenePlan(
                scene_number=2,
                scene_title="Material Detail Close-Up",
                duration_seconds=4,
                scene_description=(
                    f"A refined close-up highlighting the craftsmanship, texture, and premium finish of {product_title}."
                ),
                frame_prompt=(
                    f"Create a close-up commercial detail shot of {product_title}. "
                    "Highlight texture, fabric, stitching, material finish, and premium craftsmanship. "
                    "Keep the image realistic, crisp, and product-focused for online selling."
                ),
                transition_note="Move from the hero frame into craftsmanship detail.",
            ),
            StudioScenePlan(
                scene_number=3,
                scene_title="Lifestyle Sales Frame",
                duration_seconds=4,
                scene_description=(
                    f"A tasteful lifestyle-oriented image that keeps {product_title} as the hero while adding aspirational context."
                ),
                frame_prompt=(
                    f"Create a tasteful lifestyle marketing image of {product_title} where the product remains the hero subject. "
                    "Add subtle premium context only if it helps sell the item, while keeping the product large, visible, and realistic. "
                    f"Use the product description for guidance: {product_description[:180]}"
                ),
                transition_note="Close with an aspirational but product-first frame.",
            ),
        ]

    def _parse_json_response(self, raw_output: str) -> dict[str, Any]:
        candidate = raw_output.strip()
        if candidate.startswith("```"):
            lines = candidate.splitlines()
            if lines:
                lines = lines[1:]
            if lines and lines[-1].strip() == "```":
                lines = lines[:-1]
            candidate = "\n".join(lines).strip()
            if candidate.lower().startswith("json"):
                candidate = candidate[4:].strip()

        try:
            return json.loads(candidate)
        except json.JSONDecodeError as exc:
            raise ValueError(f"Studio planning model returned invalid JSON: {exc}") from exc
